name: Test

on: [pull_request]

jobs:
  cancel-previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  test-packages:
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.10.0'
          registry-url: https://registry.npmjs.org/

      - name: Rush install
        run: node common/scripts/install-run-rush.js install

      - name: Build packages
        run: node common/scripts/install-run-rush.js build --verbose

      - name: Test packages
        run: node common/scripts/install-run-rush.js test

      - name: Verify changes packages
        run: node common/scripts/install-run-rush.js change --verify
